//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbarquesGVI.Models.BD_A
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pruebasEmbarquesEntities : DbContext
    {
        public pruebasEmbarquesEntities()
            : base("name=pruebasEmbarquesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<embarques> embarques { get; set; }
        public virtual DbSet<embarquesDetCajas> embarquesDetCajas { get; set; }
        public virtual DbSet<embarquesDetTrans> embarquesDetTrans { get; set; }
        public virtual DbSet<Mcajas> Mcajas { get; set; }
        public virtual DbSet<paqueterias> paqueterias { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tiposSol> tiposSol { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
