//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbarquesGVI.Models.BD_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class embarquesDetTrans
    {
        public int DocEntry { get; set; }
        public string No_trans { get; set; }
    
        public virtual embarques embarques { get; set; }
    }
}
