//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbarquesGVI.Models.BD_A
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class embarques
    {
        public int DocEntry { get; set; }
        [DisplayName("Folio")]
        public string DocNum { get; set; }
        [DisplayName("Plaza")]
        public string plaza { get; set; }
        [DisplayName("Almacen")]
        public Nullable<int> almacen { get; set; }
        [DisplayName("Fecha")]
        public Nullable<System.DateTime> fecha { get; set; }
        [DisplayName("Tipo de solicitud")]
        public Nullable<int> tipoSol { get; set; }
        public Nullable<int> paqueteria { get; set; }
        [DisplayName("Número de guia")]
        public string NoGuia { get; set; }
        [DisplayName("Total de paquetes")]
        public Nullable<int> Total_Paquetes { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual embarquesDetTrans embarquesDetTrans { get; set; }
        public virtual embarquesDetCajas embarquesDetCajas { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual paqueterias paqueterias { get; set; }
        public virtual tiposSol tiposSol { get; set; }
    }
}
