//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbarquesGVI.Models.BD_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mcajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mcajas()
        {
            this.embarquesDetCajas = new HashSet<embarquesDetCajas>();
        }
    
        public int idM { get; set; }
        public Nullable<int> alto { get; set; }
        public Nullable<int> ancho { get; set; }
        public Nullable<int> largo { get; set; }
        public Nullable<int> peso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<embarquesDetCajas> embarquesDetCajas { get; set; }
    }
}
