//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbarquesGVI.Models.BD_B
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_IMTRANS
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string RequestStatus { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
        public string U_WhsCodeOr { get; set; }
        public Nullable<System.DateTime> U_FechaProgSalida { get; set; }
        public Nullable<System.DateTime> U_FechaRealSalida { get; set; }
        public string U_Prioridad { get; set; }
        public string U_CheckEntregas { get; set; }
        public string U_CheckRecepcion { get; set; }
        public string U_YaSalio { get; set; }
        public string U_Recolectado { get; set; }
        public string U_ChecadoOrigen { get; set; }
        public string U_ChecadoDestinos { get; set; }
        public string U_FinDestinos { get; set; }
        public string U_Acomodado { get; set; }
        public string U_CardCode { get; set; }
        public string U_CardName { get; set; }
        public string U_Address { get; set; }
        public Nullable<short> U_Series { get; set; }
        public Nullable<System.DateTime> U_DocDate { get; set; }
        public Nullable<System.DateTime> U_TaxDate { get; set; }
        public Nullable<short> U_GroupNum { get; set; }
        public string U_AutoEntrega { get; set; }
        public string U_AutoRecepcion { get; set; }
        public int U_TipoTrans { get; set; }
        public Nullable<int> U_BaseDocObj { get; set; }
        public Nullable<int> U_BaseDocEntry { get; set; }
        public string U_Comentarios { get; set; }
    }
}
