//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbarquesGVI.Models.BD_B
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSLP
    {
        public int SlpCode { get; set; }
        public string SlpName { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Active { get; set; }
        public string Telephone { get; set; }
        public string Mobil { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string U_UsuarioIM { get; set; }
        public string U_NomUserIM { get; set; }
        public string U_PassIM { get; set; }
        public Nullable<short> U_ASESOR { get; set; }
        public Nullable<short> U_IDTipoAsesor { get; set; }
        public string U_TipoAsesor { get; set; }
        public string U_Plaza { get; set; }
        public Nullable<System.DateTime> U_FechaBaja { get; set; }
        public int U_Status { get; set; }
        public string U_UsuarioPDA { get; set; }
        public string U_NomUserPDA { get; set; }
        public string U_PassPDA { get; set; }
        public string U_AlmPrincipal { get; set; }
        public string U_AlmCamion { get; set; }
        public int U_SigCodCte { get; set; }
        public int U_SerieCot { get; set; }
        public int U_SeriePed { get; set; }
        public int U_SerieFac { get; set; }
        public int U_SeriePag { get; set; }
        public int U_SerieDev { get; set; }
        public string U_CtaEfectivo { get; set; }
        public string U_CtaCheques { get; set; }
        public int U_CCot { get; set; }
        public int U_CPed { get; set; }
        public int U_CFac { get; set; }
        public int U_CPag { get; set; }
        public int U_CDev { get; set; }
        public string U_AgrupadorPadre { get; set; }
        public string U_WhsCodeOVD { get; set; }
        public string U_WhsCodeDVD { get; set; }
    }
}
